import Navbar from '@dashboard/components/navbar/Navbar';
import { ColorSchemeScript, Container, MantineProvider, createTheme } from '@mantine/core';
import '@mantine/core/styles.css';
import type { Metadata } from "next";
import MainMenu from './components/man-menu/MainMenu';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'cyan',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <Navbar />
          <MainMenu />
          <Container size="lg">
            {children}
          </Container>

        </MantineProvider>
      </body>
    </html>
  );
}
