import MainMenu from '@dashboard/components/main-menu/MainMenu';
import Navbar from '@dashboard/components/navbar/Navbar';
import { getGlobalConfigs } from '@database/config/data';
import { ColorSchemeScript, Container, MantineProvider, createTheme } from '@mantine/core';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { Notifications } from '@mantine/notifications';
import '@mantine/notifications/styles.css';
import type { Metadata } from "next";
import { GlobalConfigType } from 'utils/types/configs';
import HydrateData from './components/store/HydrateData';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'cyan',
  components: {
    InputWrapper: {
      styles: {
        root: {
          marginBottom: '1rem',
        },
      },
    },
    Fieldset: {
      styles: {
        legend: {
          fontWeight: 'bold',
        }
      }
    }
  },

});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = (await getGlobalConfigs() as GlobalConfigType);

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <Navbar />
          <MainMenu />
          <Container size="lg">
            {children}
          </Container>
          <Notifications />
        </MantineProvider>
        <HydrateData globalConfig={config} />
      </body>
    </html>
  );
}
